
character_pages = [
    {
        "title": "*January 26, 2022 02:23*\n🟢 Positive feedback, order amount 44£\n*Buyer:* great stuff!\n\n*January 25, 2022 23:39*\n🟢 Positive feedback, order amount 210£\n*Buyer:* great stuff!\n\n*January 25, 2022 15:10*\n🟢 Positive feedback, order amount 66£\n*Buyer:* 3DD top product and vendor\n\n*January 25, 2022 07:44*🟢 Positive feedback, order amount 120£\n*Buyer:* 5DD - probably due to royal mail delays. Looks great, very strong! Great vendor\n\n*January 24, 2022 19:29*\n🟢 Positive feedback, order amount 88£\n*Buyer:* 3DD Slightly above weight looks like great product as always"
    },
    
    {"title": "*January 24, 2022 09:42*\n🟢 Positive feedback, order amount 80£\n*Buyer:* 9DD but got it eventually and well packaged\n*January 23, 2022 02:25*\n🟢 Positive feedback, order amount 74£\n*Buyer:* Great\n*January 21, 2022 00:43*\n🟢 Positive feedback, order amount 95£\n*Buyer:* 8dd but this was due to royal mail delays, all good\n\n*January 20, 2022 13:35*\n🟢 Positive feedback, order amount 115£\n*Buyer:* Patiently waited a week to arrive, but had no concerns as never been let down before by this seller. Product top notch as always\n\n*January 20, 2022 10:30*\n🟢 Positive feedback, order amount 59£\n*Buyer:* 8DD must be cos its been baged off for over a week the dawg smells like old school dutch saying that its a very nice smoke tho also im a heavy smoker this would be ideal for anyone looking for a chill high not to intence7/10 Cheers mate will be back Update For sure got the ami and dwag mixed up Both need to be cured better for sure great smokes just no bag appeal"},
    {"title": "*January 20, 2022 05:44*\n🟢 Positive feedback, order amount 325£\n*Buyer:* 4DD all looks good though. Many thanks\n\n*January 19, 2022 16:12*\n🟢 Positive feedback, order amount 75£\n*Buyer:* Awesome\n\n*January 19, 2022 14:31*\n🟢 Positive feedback, order amount 126£\n*Buyer:* NDD bud very dry, just ok\n\n*January 19, 2022 11:25*\n🟢 Positive feedback, order amount 58£\n*Buyer:* Excellent in every sense of the word. Highly recommend\n\n*January 19, 2022 05:52*\n🟢 Positive feedback, order amount 125£\n*Buyer:* Fast safe delivery Excellent quality clean product"},
    {"title": "*January 19, 2022 01:45*\n🟢 Positive feedback, order amount 180£\n*Buyer:* 2DD cleanest acid ive ever felt very very impressed with this one\n\n*January 18, 2022 21:58*\n🟢 Positive feedback, order amount 29£\n*Buyer:* 10/10 stealth & packaging. Quick delivery.\n\n*January 18, 2022 17:03*\n🟢 Positive feedback, order amount 80£\n*Buyer:* noice\n\n*January 18, 2022 16:21*🟢 Positive feedback, order amount 135£\n*Buyer:* all looks good though. Many thanks\n\n*January 18, 2022 12:*\n🟢 Positive feedback, order amount 80£\n*Buyer:* best about"},
    {"title": "*January 18, 2022 12:00*\n🟢 Positive feedback, order amount 225£\n*Buyer:* On weight. Good quality. 7DD domestic\n\n*January 17, 2022 22:33*\n🟢 Positive feedback, order amount 345£\n*Buyer:* Great stuff with super fast delivery.\n\n*January 17, 2022 20:12*\n🟢 Positive feedback, order amount0£\n*Buyer:* always land without any problems\n\n*January 17, 2022 13:21*\n🟢 Positive feedback, order amount 234£\n*Buyer:* Fast and Fresh excellent stealth thanks highly recommended\n\n*January 17, 2022 11:11*\n🟢 Positive feedback, order amount 120£\n*Buyer:* best stuff on here"},
    {"title": "*January 16, 2022 23:12*\n🟢 Positive feedback, order amount 70£\n*Buyer:* Excellent in every sense of the word. Highly recommend\n\n*January 16, 2022 15:55*\n🟢 Positive feedback, order amount 115£\n*Buyer:* Another flawless delivery and product thanks again\n\n*January 16, 2022 09:45*\n🟢 Positive feedback, order amount 74£\n*Buyer:* Boliv cocaine 1g. was 5DD, but of a good quality when it arrived. overall very happy.\n\n*January 15, 2022 14:22*\n🟢 Positive feedback, order amount 29£\n*Buyer:* 3dd Looks really nice\n\n*January 15, 2022 01:14*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Excellent product, will return soon. Cheers."},
    {"title": "*January 14, 2022 18:32*\n🟢 Positive feedback, order amount 143£\n*Buyer:*\n\n* January 14, 2022 15:43*\n🟢 Positive feedback, order amount 145£\n*Buyer:* On weight. Good quality. 7DD domestic\n\n*January 14, 2022 12:32*\n🟢 Positive feedback, order amount 85£\n*Buyer:*\n\n*January 14, 2022 00:19*\n🟢 Positive feedback, order amount 120£\n*Buyer:* good quality and always quick delivery\n\n*January 13, 2022 16:41*\n🟢 Positive feedback, order amount 215£\n*Buyer:* Arrived after 4 days thanks"},
    {"title": "*January 13, 2022 05:07*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Took more than a week to deliver, but looks good\n\n*January 13, 2022 01:24*\n🟢 Positive feedback, order amount 215£\n*Buyer:* top vendor\n\n*January 12, 2022 18:44*\n🟢 Positive feedback, order amount 49£\n*Buyer:* Took a while, but the product is legit - A\n\n*January 12, 2022 16:49*\n🟢 Positive feedback, order amount 180£\n*Buyer*: Great stuff\n\n*January 12, 2022 10:42*\n🟢 Positive feedback, order amount 225£\n*Buyer:* arrived in good time and good stealth uk to uk DC are professional outfit have used before cheers will update once smoked some"},
    {"title": "*January 12, 2022 10:33*\n🟢 Positive feedback, order amount 55£\n*Buyer:* Respect for still sending out when WHM is closing!\n\n*January 12, 2022 07:15*\n🟢 Positive feedback, order amount 101£\n*Buyer:* Top notch. Arrived after a few days and smells like it means business! Thanks a lot, recommend seller, seems professional, and stealth was fine too.\n\n*January 12, 2022 05:33*\n🟢 Positive feedback, order amount 95£\n*Buyer:* Arrived later than expected. Packaging was perfect. Quality yet to be tested.\n\n*January 11, 2022 23:14*\n🟢 Positive feedback, order amount 109£\n*Buyer:* 3DD, top level coke. This guy has had some of the best coke on the darknet for years\n\n*January 11, 2022 19:33*\n🟢 Positive feedback, order amount 120£\n*Buyer:* Received speed NDD. havent tested yet. but looks all good. thank you."},
    {"title": "*January 11, 2022 17:55*\n🟢 Positive feedback, order amount 89£\n*Buyer:* 5DD good stealth and good sativa smoke. not glued to sofa\n\n*January 11, 2022 16:54*\n🟢 Positive feedback, order amount 136£\n*Buyer:* Not tried but looks good 3dd\n\n*January 11, 2022 16:35*\n🟢 Positive feedback, order amount 136£\n*Buyer:* Not tried but looks good 3dd\n\n*January 11, 2022 16:24*\n🟢 Positive feedback, order amount 100£\n*Buyer:* Nice one great as always cheers \n\n*January 11, 2022 13:19*\n🟢 Positive feedback, order amount 28£\n*Buyer:* Took a bit to arrive but amazing quality gear as always. Ignore the people giving low rating, dcuk has been around and highly trusted for years!"},
    {"title": "*January 11, 2022 09:00*\n🟢 Positive feedback, order amount 28£\n*Buyer:* Took a bit to arrive but amazing quality gear as always. Ignore the people giving low rating, dcuk has been around and highly trusted for years!\n\n*January 11, 2022 06:35*\n🟢 Positive feedback, order amount 59£\n*Buyer:* Would buy again\n\n*January 11, 2022 01:20*\n🟢 Positive feedback, order amount 59£\n*Buyer*: Would buy again\n\n*January 10, 2022 23:26*\n🟢 Positive feedback, order amount 120£\n*Buyer:* Good stealth and product as usual from dcuk\n\n*January 10, 2022 19:24*\n🟢 Positive feedback, order amount 120£\n*Buyer:* Good stealth and product as usual from dcuk"},
    {"title": "*January 10, 2022 15:15*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Not tried yet but all arrived nice and stealthy and tabs look genuine.\n\n*January 10, 2022 15:15*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Not tried yet but all arrived nice and stealthy and tabs look genuine.\n\n*January 10, 2022 14:22*\n🟢 Positive feedback, order amount 173£\n*Buyer:* Awesome MDMA\n\n*January 10, 2022 12:14*\n🟢 Positive feedback, order amount 32£\n*Buyer*: quick and proffesional service\n\n*January 10, 2022 11:22*\n🟢 Positive feedback, order amount 180£\n*Buyer*: Quality Stardawg!!"},
    {"title": "*January 09, 2022 22:45*\n🟢 Positive feedback, order amount 173£\n*Buyer:* ............ ❤️\n\nJanuary 09, 2022 09:56\n🟢 Positive feedback, order amount 240£\n*Buyer:* Usually would leave 5 stars for DCUK but its taken 12 days for it to arrive.. I can understand that due to post but messaged twice to see if there was a problem and no response .. which is unusual since always been good at comms before.. anyway arrived and weight spot on ... just a shame had to wait 12 days wondering if it was even going to turn up - DCUK still truswtorthy then - could just do with responding to genuine messages.\n\n*January 08, 2022 16:43*\n🟢 Positive feedback, order amount 59£\n*Buyer:* Trustworthy, as always. Thank you!\n\n*January 08, 2022 00:56*\n🟢 Positive feedback, order amount 103£\n*Buyer:* Great weed, worth the wait, thanks man\n\n*January 07, 2022 20:15*\n🟢 Positive feedback, order amount 110£\n*Buyer:* 3DD. All good. Quality products."},
    {"title": "*January 07, 2022 16:21*\n🟢 Positive feedback, order amount 69£\n*Buyer:* 2DD my go to vendor\n\n*January 07, 2022 12:42*\n🟢 Positive feedback, order amount 120£\n*Buyer:*\n\n*January 06, 2022 13:55*\n🟢 Positive feedback, order amount 290£\n*Buyer:* Good coke and stealth\n\n*January 06, 2022 09:21*\n🟢 Positive feedback, order amount 69£\n*Buyer:* Nice and fast!!\n\n*January 05, 2022 11:21*\n🟢 Positive feedback, order amount 33£\n*Buyer:* Not bad"},
    {"title": "*January 05, 2022 06:55*\n🟢 Positive feedback, order amount 143£\n*Buyer:* 2DD, good gear, cant complain DCs a top vendor!!!\n\n*January 04, 2022 15:32*\n🟢 Positive feedback, order amount 90£\n*Buyer:* thanks!\n\n*January 04, 2022 10:55*\n🟢 Positive feedback, order amount 59£\n*Buyer:* Awesome as always\n\n*January 04, 2022 09:21*\n🟢 Positive feedback, order amount 228£\n*Buyer:* Fast shipping quality product\n\n*January 03, 2022 07:05*\n🟢 Positive feedback, order amount 314£\n*Buyer:* Thanks top stuff"},
    {"title": "*January 03, 2022 00:25*\n🟢 Positive feedback, order amount 113£\n*Buyer:* 4DD Ordered Changa but received powder. No big deal though\n\n*January 01, 2022 14:05*\n🟢 Positive feedback, order amount 240£\n*Buyer:* Amnesia Haze. Nice\n\n*December 31, 2021 00:48*\n🟢 Positive feedback, order amount 117£\n*Buyer:* Received but took 4dd, thanks\n\n*December 31, 2021 00:45*\n🟢 Positive feedback, order amount 91£\n*Buyer:* Recive all  good .nice quality . 5\n\n*December 30, 2021 15:48*\n🟢 Positive feedback, order amount 100£\n*Buyer:* Super"},
    {"title": "*December 30, 2021 08:55*\n🟢 Positive feedback, order amount 74£\n*Buyer:* That was quite some delay! But i got it in the end, so thanks, coke is good.\n\n*December 29, 2021 09:31*\n🟢 Positive feedback, order amount 117£\n*Buyer:* Decent gear\n\n*December 28, 2021 22:52*\n🟢 Positive feedback, order amount 74£\n*Buyer:* Perfect bro\n\n*December 28, 2021 19:08*\n🟢 Positive feedback, order amount 143£\n*Buyer:* Amazing\n\n*December 28, 2021 15:04*\n🟢 Positive feedback, order amount 215£\n*Buyer:* Super speed"},
    {"title": "*December 28, 2021 01:48*\n🟢 Positive feedback, order amount 100£\n*Buyer:* 4DD. All good!\n\n*December 27, 2021 21:10*\n🟢 Positive feedback, order amount 240£\n*Buyer:* Greattttt\n\n*December 27, 2021 18:21*\n🟢 Positive feedback, order amount 117£\n*Buyer:* 3DD great stealth \n\n*December 27, 2021 16:23*\n🟢 Positive feedback, order amount 143£\n*Buyer:* One word.... perfect!!!!!!!!\n\n*December 27, 2021 15:49*\n🟢 Positive feedback, order amount 28£\n*Buyer:*"},
    {"title": "*December 27, 2021 09:48*\n🟢 Positive feedback, order amount 112£\n*Buyer:* Great. Thank you. I will be back for sure\n\n*December 27, 2021 00:32*\n🟢 Positive feedback, order amount 112£\n*Buyer:* Lovely looking little rascals 3dd\n\n*December 26, 2021 07:55*\n🟢 Positive feedback, order amount 582£\n*Buyer:* Vendor and product are amazing, royal mail are taking the piss with delivery tho 5 DD but great comm from vendor and product is always amazing ⭐️⭐️⭐️⭐️⭐️\n\n*December 26, 2021 00:19*\n🟢 Positive feedback, order amount 173£\n*Buyer:* All good thanks bro\n\n*December 25, 2021 23:18*\n🟢 Positive feedback, order amount 87£\n*Buyer:* A1 as always. These guys are at the top"},
    {"title": "*December 25, 2021 15:20*\n🟢 Positive feedback, order amount 42\n*Buyer:* Took a week to arrive but excellent quality \n\n*December 24, 2021 14:2*\n🟢 Positive feedback, order amount 173\n*Buyer:* Love you bro \n\n*December 23, 2021 10:5*\n🟢 Positive feedback, order amount 87\n*Buyer:* Absolutely great service thanks guys\n\n*December 22, 2021 23:5*\n🟢 Positive feedback, order amount 35\n*Buyer:* Clean press, recommend as alway\n\n*December 22, 2021 20:4*\n🟢 Positive feedback, order amount 57\n*Buyer:* Smooth as always, trust these professionals"},

    {
        "title": "*January 11, 2022 22:45*\n⚪️ Neutral feedback, order amount 59£\n*Buyer:* 14DD and when it turned up it was lumpy M Cat so it went straight in the bin.\n\n*December 30, 2021 00:34*\n⚪️ Neutral feedback, order amount 33£\n*Buyer:* Been a week with no drop. Hopefully soon. Seller has replied saying will reship if nothing comes soon but was need for a fest this Saturday. Will change to full positive if it comes.\n\n *December 26, 2021 23:37*\n⚪️ Neutral feedback, order amount 360£\n*Buyer:* I received my order but the seller does not reply to any messages lol thanks !!!\n\n*December 15, 2021 12:48*\n⚪️ Neutral feedback, order amount 240£\n*Buyer:* ALL OK!\n\n*December 14, 2021 18:29*\n⚪️ Neutral feedback, order amount 80£\n*Buyer:* Waiting for delivery"
    },
    
    {
        "title": "*December 08, 2021 10:39*\n⚪️ Neutral feedback, order amount 143£\n*Buyer:* All ok!!!!\n\n*December 02, 2021 23:55*\n⚪️ Neutral feedback, order amount 57£\n*Buyer:* Products not quality…\n\n*December 02, 2021 09:43*\n⚪️ Neutral feedback, order amount 29£\n*Buyer:* Really good quality speed."
    },
     
    {
        "title": "*January 11, 2022 22:14*\n🔴 Negative feedback, order amount 75£\n*Buyer:* Absolute scam...placed the order weeks ago and nothing arrive, since then I've messaged the seller twice and have been completely ignored. Highly recommend shopping somewhere else.\n\n*December 16, 2021 15:48*\n🔴 Negative feedback, order amount 118£\n*Buyer:* Very disappointed with this seller. Awful customer service and support. I've never had any problems with other bots. If you are thinking of using @DCdutchconnectionUKbot , think again. Look elsewhere\n\n*December 14, 2021 22:54*\n🔴 Negative feedback, order amount 80£\n*Buyer:* Order never arrived\n\n*December 03, 2021 20:17*\n🔴 Negative feedback, order amount 41£\n*Buyer:* Avoid. I never received order, and seller never replied to my messages."
    }

]

Neutral = [
    {
        "title": "*January 11, 2022 22:45*\n⚪️ Neutral feedback, order amount 59£\n*Buyer:* 14DD and when it turned up it was lumpy M Cat so it went straight in the bin.\n\n*December 30, 2021 00:34*\n⚪️ Neutral feedback, order amount 33£\n*Buyer:* Been a week with no drop. Hopefully soon. Seller has replied saying will reship if nothing comes soon but was need for a fest this Saturday. Will change to full positive if it comes.\n\n *December 26, 2021 23:37*\n⚪️ Neutral feedback, order amount 360£\n*Buyer:* I received my order but the seller does not reply to any messages lol thanks !!!\n\n*December 15, 2021 12:48*\n⚪️ Neutral feedback, order amount 240£\n*Buyer:* ALL OK!\n\n*December 14, 2021 18:29*\n⚪️ Neutral feedback, order amount 80£\n*Buyer:* Waiting for delivery"
    },
    
    {
        "title": "*December 08, 2021 10:39*\n⚪️ Neutral feedback, order amount 143£\n*Buyer:* All ok!!!!\n\n*December 02, 2021 23:55*\n⚪️ Neutral feedback, order amount 57£\n*Buyer:* Products not quality…\n\n*December 02, 2021 09:43*\n⚪️ Neutral feedback, order amount 29£\n*Buyer:* Really good quality speed."
    }
]

Negative = [
    
    {
        "title": "*January 11, 2022 22:14*\n🔴 Negative feedback, order amount 75£\n*Buyer:* Absolute scam...placed the order weeks ago and nothing arrive, since then I've messaged the seller twice and have been completely ignored. Highly recommend shopping somewhere else.\n\n*December 16, 2021 15:48*\n🔴 Negative feedback, order amount 118£\n*Buyer:* Very disappointed with this seller. Awful customer service and support. I've never had any problems with other bots. If you are thinking of using @DCdutchconnectionUKbot , think again. Look elsewhere\n\n*December 14, 2021 22:54*\n🔴 Negative feedback, order amount 80£\n*Buyer:* Order never arrived\n\n*December 03, 2021 20:17*\n🔴 Negative feedback, order amount 41£\n*Buyer:* Avoid. I never received order, and seller never replied to my messages."
    }

]


Positive = [
    {
        "title": "*January 26, 2022 02:23*\n🟢 Positive feedback, order amount 44£\n*Buyer:* great stuff!\n\n*January 25, 2022 23:39*\n🟢 Positive feedback, order amount 210£\n*Buyer:* great stuff!\n\n*January 25, 2022 15:10*\n🟢 Positive feedback, order amount 66£\n*Buyer:* 3DD top product and vendor\n\n*January 25, 2022 07:44*🟢 Positive feedback, order amount 120£\n*Buyer:* 5DD - probably due to royal mail delays. Looks great, very strong! Great vendor\n\n*January 24, 2022 19:29*\n🟢 Positive feedback, order amount 88£\n*Buyer:* 3DD Slightly above weight looks like great product as always"
    },
    
    {"title": "*January 24, 2022 09:42*\n🟢 Positive feedback, order amount 80£\n*Buyer:* 9DD but got it eventually and well packaged\n*January 23, 2022 02:25*\n🟢 Positive feedback, order amount 74£\n*Buyer:* Great\n*January 21, 2022 00:43*\n🟢 Positive feedback, order amount 95£\n*Buyer:* 8dd but this was due to royal mail delays, all good\n\n*January 20, 2022 13:35*\n🟢 Positive feedback, order amount 115£\n*Buyer:* Patiently waited a week to arrive, but had no concerns as never been let down before by this seller. Product top notch as always\n\n*January 20, 2022 10:30*\n🟢 Positive feedback, order amount 59£\n*Buyer:* 8DD must be cos its been baged off for over a week the dawg smells like old school dutch saying that its a very nice smoke tho also im a heavy smoker this would be ideal for anyone looking for a chill high not to intence7/10 Cheers mate will be back Update For sure got the ami and dwag mixed up Both need to be cured better for sure great smokes just no bag appeal"},
    {"title": "*January 20, 2022 05:44*\n🟢 Positive feedback, order amount 325£\n*Buyer:* 4DD all looks good though. Many thanks\n\n*January 19, 2022 16:12*\n🟢 Positive feedback, order amount 75£\n*Buyer:* Awesome\n\n*January 19, 2022 14:31*\n🟢 Positive feedback, order amount 126£\n*Buyer:* NDD bud very dry, just ok\n\n*January 19, 2022 11:25*\n🟢 Positive feedback, order amount 58£\n*Buyer:* Excellent in every sense of the word. Highly recommend\n\n*January 19, 2022 05:52*\n🟢 Positive feedback, order amount 125£\n*Buyer:* Fast safe delivery Excellent quality clean product"},
    {"title": "*January 19, 2022 01:45*\n🟢 Positive feedback, order amount 180£\n*Buyer:* 2DD cleanest acid ive ever felt very very impressed with this one\n\n*January 18, 2022 21:58*\n🟢 Positive feedback, order amount 29£\n*Buyer:* 10/10 stealth & packaging. Quick delivery.\n\n*January 18, 2022 17:03*\n🟢 Positive feedback, order amount 80£\n*Buyer:* noice\n\n*January 18, 2022 16:21*🟢 Positive feedback, order amount 135£\n*Buyer:* all looks good though. Many thanks\n\n*January 18, 2022 12:*\n🟢 Positive feedback, order amount 80£\n*Buyer:* best about"},
    {"title": "*January 18, 2022 12:00*\n🟢 Positive feedback, order amount 225£\n*Buyer:* On weight. Good quality. 7DD domestic\n\n*January 17, 2022 22:33*\n🟢 Positive feedback, order amount 345£\n*Buyer:* Great stuff with super fast delivery.\n\n*January 17, 2022 20:12*\n🟢 Positive feedback, order amount0£\n*Buyer:* always land without any problems\n\n*January 17, 2022 13:21*\n🟢 Positive feedback, order amount 234£\n*Buyer:* Fast and Fresh excellent stealth thanks highly recommended\n\n*January 17, 2022 11:11*\n🟢 Positive feedback, order amount 120£\n*Buyer:* best stuff on here"},
    {"title": "*January 16, 2022 23:12*\n🟢 Positive feedback, order amount 70£\n*Buyer:* Excellent in every sense of the word. Highly recommend\n\n*January 16, 2022 15:55*\n🟢 Positive feedback, order amount 115£\n*Buyer:* Another flawless delivery and product thanks again\n\n*January 16, 2022 09:45*\n🟢 Positive feedback, order amount 74£\n*Buyer:* Boliv cocaine 1g. was 5DD, but of a good quality when it arrived. overall very happy.\n\n*January 15, 2022 14:22*\n🟢 Positive feedback, order amount 29£\n*Buyer:* 3dd Looks really nice\n\n*January 15, 2022 01:14*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Excellent product, will return soon. Cheers."},
    {"title": "*January 14, 2022 18:32*\n🟢 Positive feedback, order amount 143£\n*Buyer:*\n\n* January 14, 2022 15:43*\n🟢 Positive feedback, order amount 145£\n*Buyer:* On weight. Good quality. 7DD domestic\n\n*January 14, 2022 12:32*\n🟢 Positive feedback, order amount 85£\n*Buyer:*\n\n*January 14, 2022 00:19*\n🟢 Positive feedback, order amount 120£\n*Buyer:* good quality and always quick delivery\n\n*January 13, 2022 16:41*\n🟢 Positive feedback, order amount 215£\n*Buyer:* Arrived after 4 days thanks"},
    {"title": "*January 13, 2022 05:07*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Took more than a week to deliver, but looks good\n\n*January 13, 2022 01:24*\n🟢 Positive feedback, order amount 215£\n*Buyer:* top vendor\n\n*January 12, 2022 18:44*\n🟢 Positive feedback, order amount 49£\n*Buyer:* Took a while, but the product is legit - A\n\n*January 12, 2022 16:49*\n🟢 Positive feedback, order amount 180£\n*Buyer*: Great stuff\n\n*January 12, 2022 10:42*\n🟢 Positive feedback, order amount 225£\n*Buyer:* arrived in good time and good stealth uk to uk DC are professional outfit have used before cheers will update once smoked some"},
    {"title": "*January 12, 2022 10:33*\n🟢 Positive feedback, order amount 55£\n*Buyer:* Respect for still sending out when WHM is closing!\n\n*January 12, 2022 07:15*\n🟢 Positive feedback, order amount 101£\n*Buyer:* Top notch. Arrived after a few days and smells like it means business! Thanks a lot, recommend seller, seems professional, and stealth was fine too.\n\n*January 12, 2022 05:33*\n🟢 Positive feedback, order amount 95£\n*Buyer:* Arrived later than expected. Packaging was perfect. Quality yet to be tested.\n\n*January 11, 2022 23:14*\n🟢 Positive feedback, order amount 109£\n*Buyer:* 3DD, top level coke. This guy has had some of the best coke on the darknet for years\n\n*January 11, 2022 19:33*\n🟢 Positive feedback, order amount 120£\n*Buyer:* Received speed NDD. havent tested yet. but looks all good. thank you."},
    {"title": "*January 11, 2022 17:55*\n🟢 Positive feedback, order amount 89£\n*Buyer:* 5DD good stealth and good sativa smoke. not glued to sofa\n\n*January 11, 2022 16:54*\n🟢 Positive feedback, order amount 136£\n*Buyer:* Not tried but looks good 3dd\n\n*January 11, 2022 16:35*\n🟢 Positive feedback, order amount 136£\n*Buyer:* Not tried but looks good 3dd\n\n*January 11, 2022 16:24*\n🟢 Positive feedback, order amount 100£\n*Buyer:* Nice one great as always cheers \n\n*January 11, 2022 13:19*\n🟢 Positive feedback, order amount 28£\n*Buyer:* Took a bit to arrive but amazing quality gear as always. Ignore the people giving low rating, dcuk has been around and highly trusted for years!"},
    {"title": "*January 11, 2022 09:00*\n🟢 Positive feedback, order amount 28£\n*Buyer:* Took a bit to arrive but amazing quality gear as always. Ignore the people giving low rating, dcuk has been around and highly trusted for years!\n\n*January 11, 2022 06:35*\n🟢 Positive feedback, order amount 59£\n*Buyer:* Would buy again\n\n*January 11, 2022 01:20*\n🟢 Positive feedback, order amount 59£\n*Buyer*: Would buy again\n\n*January 10, 2022 23:26*\n🟢 Positive feedback, order amount 120£\n*Buyer:* Good stealth and product as usual from dcuk\n\n*January 10, 2022 19:24*\n🟢 Positive feedback, order amount 120£\n*Buyer:* Good stealth and product as usual from dcuk"},
    {"title": "*January 10, 2022 15:15*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Not tried yet but all arrived nice and stealthy and tabs look genuine.\n\n*January 10, 2022 15:15*\n🟢 Positive feedback, order amount 80£\n*Buyer:* Not tried yet but all arrived nice and stealthy and tabs look genuine.\n\n*January 10, 2022 14:22*\n🟢 Positive feedback, order amount 173£\n*Buyer:* Awesome MDMA\n\n*January 10, 2022 12:14*\n🟢 Positive feedback, order amount 32£\n*Buyer*: quick and proffesional service\n\n*January 10, 2022 11:22*\n🟢 Positive feedback, order amount 180£\n*Buyer*: Quality Stardawg!!"},
    {"title": "*January 09, 2022 22:45*\n🟢 Positive feedback, order amount 173£\n*Buyer:* ............ ❤️\n\nJanuary 09, 2022 09:56\n🟢 Positive feedback, order amount 240£\n*Buyer:* Usually would leave 5 stars for DCUK but its taken 12 days for it to arrive.. I can understand that due to post but messaged twice to see if there was a problem and no response .. which is unusual since always been good at comms before.. anyway arrived and weight spot on ... just a shame had to wait 12 days wondering if it was even going to turn up - DCUK still truswtorthy then - could just do with responding to genuine messages.\n\n*January 08, 2022 16:43*\n🟢 Positive feedback, order amount 59£\n*Buyer:* Trustworthy, as always. Thank you!\n\n*January 08, 2022 00:56*\n🟢 Positive feedback, order amount 103£\n*Buyer:* Great weed, worth the wait, thanks man\n\n*January 07, 2022 20:15*\n🟢 Positive feedback, order amount 110£\n*Buyer:* 3DD. All good. Quality products."},
    {"title": "*January 07, 2022 16:21*\n🟢 Positive feedback, order amount 69£\n*Buyer:* 2DD my go to vendor\n\n*January 07, 2022 12:42*\n🟢 Positive feedback, order amount 120£\n*Buyer:*\n\n*January 06, 2022 13:55*\n🟢 Positive feedback, order amount 290£\n*Buyer:* Good coke and stealth\n\n*January 06, 2022 09:21*\n🟢 Positive feedback, order amount 69£\n*Buyer:* Nice and fast!!\n\n*January 05, 2022 11:21*\n🟢 Positive feedback, order amount 33£\n*Buyer:* Not bad"},
    {"title": "*January 05, 2022 06:55*\n🟢 Positive feedback, order amount 143£\n*Buyer:* 2DD, good gear, cant complain DCs a top vendor!!!\n\n*January 04, 2022 15:32*\n🟢 Positive feedback, order amount 90£\n*Buyer:* thanks!\n\n*January 04, 2022 10:55*\n🟢 Positive feedback, order amount 59£\n*Buyer:* Awesome as always\n\n*January 04, 2022 09:21*\n🟢 Positive feedback, order amount 228£\n*Buyer:* Fast shipping quality product\n\n*January 03, 2022 07:05*\n🟢 Positive feedback, order amount 314£\n*Buyer:* Thanks top stuff"},
    {"title": "*January 03, 2022 00:25*\n🟢 Positive feedback, order amount 113£\n*Buyer:* 4DD Ordered Changa but received powder. No big deal though\n\n*January 01, 2022 14:05*\n🟢 Positive feedback, order amount 240£\n*Buyer:* Amnesia Haze. Nice\n\n*December 31, 2021 00:48*\n🟢 Positive feedback, order amount 117£\n*Buyer:* Received but took 4dd, thanks\n\n*December 31, 2021 00:45*\n🟢 Positive feedback, order amount 91£\n*Buyer:* Recive all  good .nice quality . 5\n\n*December 30, 2021 15:48*\n🟢 Positive feedback, order amount 100£\n*Buyer:* Super"},
    {"title": "*December 30, 2021 08:55*\n🟢 Positive feedback, order amount 74£\n*Buyer:* That was quite some delay! But i got it in the end, so thanks, coke is good.\n\n*December 29, 2021 09:31*\n🟢 Positive feedback, order amount 117£\n*Buyer:* Decent gear\n\n*December 28, 2021 22:52*\n🟢 Positive feedback, order amount 74£\n*Buyer:* Perfect bro\n\n*December 28, 2021 19:08*\n🟢 Positive feedback, order amount 143£\n*Buyer:* Amazing\n\n*December 28, 2021 15:04*\n🟢 Positive feedback, order amount 215£\n*Buyer:* Super speed"},
    {"title": "*December 28, 2021 01:48*\n🟢 Positive feedback, order amount 100£\n*Buyer:* 4DD. All good!\n\n*December 27, 2021 21:10*\n🟢 Positive feedback, order amount 240£\n*Buyer:* Greattttt\n\n*December 27, 2021 18:21*\n🟢 Positive feedback, order amount 117£\n*Buyer:* 3DD great stealth \n\n*December 27, 2021 16:23*\n🟢 Positive feedback, order amount 143£\n*Buyer:* One word.... perfect!!!!!!!!\n\n*December 27, 2021 15:49*\n🟢 Positive feedback, order amount 28£\n*Buyer:*"},
    {"title": "*December 27, 2021 09:48*\n🟢 Positive feedback, order amount 112£\n*Buyer:* Great. Thank you. I will be back for sure\n\n*December 27, 2021 00:32*\n🟢 Positive feedback, order amount 112£\n*Buyer:* Lovely looking little rascals 3dd\n\n*December 26, 2021 07:55*\n🟢 Positive feedback, order amount 582£\n*Buyer:* Vendor and product are amazing, royal mail are taking the piss with delivery tho 5 DD but great comm from vendor and product is always amazing ⭐️⭐️⭐️⭐️⭐️\n\n*December 26, 2021 00:19*\n🟢 Positive feedback, order amount 173£\n*Buyer:* All good thanks bro\n\n*December 25, 2021 23:18*\n🟢 Positive feedback, order amount 87£\n*Buyer:* A1 as always. These guys are at the top"},
    {"title": "*December 25, 2021 15:20*\n🟢 Positive feedback, order amount 42\n*Buyer:* Took a week to arrive but excellent quality \n\n*December 24, 2021 14:2*\n🟢 Positive feedback, order amount 173\n*Buyer:* Love you bro \n\n*December 23, 2021 10:5*\n🟢 Positive feedback, order amount 87\n*Buyer:* Absolutely great service thanks guys\n\n*December 22, 2021 23:5*\n🟢 Positive feedback, order amount 35\n*Buyer:* Clean press, recommend as alway\n\n*December 22, 2021 20:4*\n🟢 Positive feedback, order amount 57\n*Buyer:* Smooth as always, trust these professionals"},
]